apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nvidia-driver-installer
  namespace: kube-system
  labels:
    k8s-app: nvidia-driver-installer
spec:
  selector:
    matchLabels:
      k8s-app: nvidia-driver-installer
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: nvidia-driver-installer
        k8s-app: nvidia-driver-installer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: accelerator
                    operator: Exists
      tolerations:
        - operator: "Exists"
      volumes:
        - name: dev
          hostPath:
            path: /dev
        - name: nvidia-install-dir-host
          hostPath:
            path: /home/kubernetes/bin/nvidia
        - name: root-mount
          hostPath:
            path: /
      initContainers:
        - image: brianporeilly/k3os-nvidia-driver-installer:0.2.0
          name: nvidia-driver-installer
          resources:
            requests:
              cpu: 0.15
          securityContext:
            privileged: true
          env:
            - name: NVIDIA_INSTALL_DIR_HOST
              value: /home/kubernetes/bin/nvidia
            - name: NVIDIA_INSTALL_DIR_CONTAINER
              value: /usr/local/nvidia
            - name: ROOT_MOUNT_DIR
              value: /root
          volumeMounts:
            - name: nvidia-install-dir-host
              mountPath: /usr/local/nvidia
            - name: dev
              mountPath: /dev
            - name: root-mount
              mountPath: /root
      containers:
        - image: "gcr.io/google-containers/pause:2.0"
          name: pause
